services:
  backend:
    build: .
    image: backend:latest
    ports:
      - "3007:3007"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: